### ISSUE TITLE
.po file not compatible with PoEdit

### ISSUE THREAD

**Issue by birama** [openpetra/openpetra#150]
Hi all,
I have installed PoEdit for OpenPetra translation but I cannot open the .po openpetra's file with it . Can you help please.
PS: I plan to traduct the soft before using it.

**Comment by tpokorra** [comment]
Hello @birama, which version of PoEdit are you using? on Windows or Linux?
I just tried with PoEdit 1.8.7 on Fedora, and I was able to open the file downloaded from https://weblate.openpetra.org/download/openpetra/openpetra/fr/

What kind of error do you get when you open the file in PoEdit?

PS: Please be aware that OpenPetra is still in Beta, and the texts might still change. So it is a moving target. I hope you are not investing too much time, before you can determine if it actually works for you.

**Comment by birama** [comment]
Hi,

I use Pedit's  1.8.7 version on Windows.

I can open the file you are posted in the link on your response.

**Comment by tpokorra** [comment]
where did you get the .po file from, that file which did not work?

**Comment by stradarius** [comment]
I suggest to close this issue as resolved or won't resolve because neither po-files nor weblate are used anymore [1]. Also the weblate-link mentioned above by tpokorra is not valid anymore.

If someone likes to translate it is now needed to translate [2] and create a pull request at github (procedure as mentioned by [1]).

[1] https://wiki.openpetra.org/index.php?title=Documentation_for_Translators
[2] https://github.com/openpetra/openpetra/blob/master/js-client/locales/en/common.json

**Comment by tpokorra** [comment]
thanks @stradarius!
