### ISSUE TITLE
No longer supported library.

### ISSUE THREAD

**Issue by Lukas2112** [openpetra/openpetra#593]
![openpetra](https://user-images.githubusercontent.com/47597136/108626722-eea69680-7451-11eb-939b-bb07439c9739.png)

**Comment by tpokorra** [comment]
you are refering to this message: 

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

see also https://www.npmjs.com/package/har-validator and details at https://github.com/ahmadnassri/node-har-validator/issues/173

cypress requires request which requires har-validator

```
-bash-4.2$ npm ls har-validator
openpetra-client-js@2018.2.0 /home/op_dev/openpetra/js-client
`-- cypress@5.6.0
  `-- @cypress/request@2.88.5
    `-- har-validator@5.1.5 
```

so we are looking at https://www.npmjs.com/package/@cypress/request and https://github.com/cypress-io/request

Since this is just used for running integration tests with Cypress, I am not so concerned about the deprecated library.

I have run `npm update` to solve the lodash vulnerabilities.
